apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: skaffold

test:
  - image: ariqmbrilian/public-image
    custom:
    - command: echo This is a custom test commmand!
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: ariqmbrilian/public-image
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
  local: {}
manifests:
  rawYaml:
    - k8s/*.yaml